language: node_js

node_js:
  - 6.0

before_install:
- echo "overwritten before_install"

install:
- npm install

script:
- npm test

after_success:
- echo "overwritten after_success step"

after_failure:
- echo "overwritten after_failure step"
